version: '3.4'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: AAaa123ilola#
      POSTGRES_USER: ilola
      POSTGRES_DB: LAB_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
